src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\OneToMany(targetEntity=Ride::class, mappedBy="user", orphanRemoval=true)
     */
    private $rides;

    public function __construct()
    {
        $this->rides = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection|Ride[]
     */
    public function getRides(): Collection
    {
        return $this->rides;
    }

    public function addRide(Ride $ride): self
    {
        if (!$this->rides->contains($ride)) {
            $this->rides[] = $ride;
            $ride->setUser($this);
        }

        return $this;
    }

    public function removeRide(Ride $ride): self
    {
        if ($this->rides->removeElement($ride)) {
            // set the owning side to null (unless already changed)
            if ($ride->getUser() === $this) {
                $ride->setUser(null);
            }
        }

        return $this;
    }

    public function getFullName(): string
    {
        return $this->getFirstName() . ' ' . $this->getLastName();
    }
}

templates/layouts/partials/_flash_messages.html.twig
<div class="text-center">
	{% for type, messages in app.flashes %}
		{% for message in messages %}
			<div class=" container mt-3 alert alert-{{ type }} alert-dismissible" role="alert">
				<button type="button" class="btn-close" data-bs-dismiss="alert"></button>
				{{ message }}
			</div>
		{% endfor %}
	{% endfor %}
</div>

templates/layouts/partials/_formRide.html.twig
<div class="container bg-light rounded formRide">
	<div class="col-md-6 mx-auto">
{{ form_start(formRideCreate, {attr: {novalidate: 'novalidate'}}) }}



		<div class="row">
			{% if (app.request.attributes.get('_route') == 'app_ride_create') %}
				<div class="mx-auto rounded-3">
					<h1 class="text-center" data-aos="zoom-in-down" data-aos-duration="1000">Création d'une sortie !</h1>
				</h1>
			</div>
			{% else %}
			<div class="mx-auto rounded">
				<h1 class="text-center" data-aos="zoom-in-down" data-aos-duration="1000">Modifier la sortie:<br>
					{{ ride.title }}
			</div>
			{% endif %}

			<div class="col-md-6">
				{{ form_row(formRideCreate.title) }}
				{{ form_row(formRideCreate.departureCity) }}
				{{ form_row(formRideCreate.Date) }}
				{{ form_row(formRideCreate.departureTime) }}
				{{ form_row(formRideCreate.category) }}
			</div>
			<div class="col-md-6">
				{{ form_row(formRideCreate.department) }}
				{{ form_row(formRideCreate.cityOfArrival) }}
				{{ form_row(formRideCreate.positiveElevation) }}
				{{ form_row(formRideCreate.mileage) }}
			</div>
			{{ form_row(formRideCreate.description) }}
		</div>
		{% if (app.request.attributes.get('_route') == 'app_ride_create') %}
			<div class="d-grid gap-2">
				<input type="submit" value="Créer la sortie" class="btn btn-primary mb-5" formnovalidate>
			</div>
		{% else %}
			<div class="d-grid gap-2">
				<input type="submit" value="Modifier la sortie" class="btn btn-primary mb-5" formnovalidate>
			</div>
		{% endif %}
		{{ form_end(formRideCreate) }}
	</div>
</div>

templates/layouts/partials/_nav.html.twig
<nav class="navbar navbar-expand-lg " aria-label="Eighth navbar example">
	<div class="container">
<a class="navbar-brand text-danger" href="{{ path('app_home') }}"><img src="{{ asset('build/images/rideCM.png') }}" width="100" height="30">


		</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarsExample07">
			<ul class="navbar-nav me-auto mb-2 mb-lg-0">
				{% if app.user %}
					<li class="nav-item">
						<a class="nav-link active text-white link-nav" aria-current="page" href="{{ path('app_ride_create') }}">Proposer une sortie</a>
					</li>
				{% endif %}
				<li class="nav-item">
					<a class="nav-link active text-white link-nav" href="{{ path('app_ride') }}">toutes les sorties</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link text-white text-xl link-nav" href="#" id="dropdown07" data-bs-toggle="dropdown" aria-expanded="false">Plus encore</a>
					<ul class="dropdown-menu" aria-labelledby="dropdown07">
						<li>
							<a class="dropdown-item link-nav" href="#">Vente matériels d'occasion</a>
						</li>
						<li>
							<a class="dropdown-item link-nav" href="#">échanges d'astuces</a>
						</li>
						<li>
							<a class="dropdown-item link-nav" href="#">Conseils d'entrainements</a>
						</li>
					</ul>
				</li>
			</ul>
			<ul class="navbar-nav  mb-2 mb-lg-0">
				{% if not app.user %}
					<li class="nav-item">
						<a class="nav-link text-white link-nav" href="{{ path ('app_login') }}">Connexion</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link-nav" href="{{ path ('app_register') }}">Inscription</a>
					</li>
				{% endif %}
				{% if app.user %}
					<li class="nav-item">
						<a class="nav-link link-nav" href="{{ path ('app_logout') }}">Deconnexion</a>
					</li>
					<li class="nav-item mt-2">
                        <span class="textUser ml-5">
                            Bonjour
                            {{ app.user.fullName }}
                        </span>
                    </li>

				{% endif %}
			</ul>
		</div>
	</div>
</nav>

templates/layouts/partials/footer.html.twig
<div class="container mt-5">
	<footer class="py-5 ">
		<div class="row footer card-header rounded border-top">
			<div class="col-2">
				<h5 class="text-white">Section</h5>
				<ul class="nav flex-column ">
					<li class="nav-item mb-2">
						<a href="{{ path('app_home') }}" class="nav-link p-0 text-white">Acceuil</a>
					</li>
					<li class="nav-item mb-2">
						<a href="{{ path('app_ride') }}" class="nav-link p-0 text-white">Toutes les sorties</a>
					</li>
					<li class="nav-item mb-2">
						<a href="{{ path('app_login') }}" class="nav-link p-0 text-white">Connexion</a>
					</li>
					<li class="nav-item mb-2">
						<a href="{{ path('app_register') }}" class="nav-link p-0  text-white">Inscription</a>
					</li>
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">A propos</a>
					</li>
				</ul>
			</div>
			<div class="col-2">
				<h5 class="text-white">Section</h5>
				<ul class="nav flex-column">
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">Home</a>
					</li>
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">Features</a>
					</li>
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">Pricing</a>
					</li>
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">FAQs</a>
					</li>
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">About</a>
					</li>
				</ul>
			</div>
			<div class="col-2">
				<h5 class="text-white">Section</h5>
				<ul class="nav flex-column">
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">Home</a>
					</li>
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">Features</a>
					</li>
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">Pricing</a>
					</li>
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">FAQs</a>
					</li>
					<li class="nav-item mb-2">
						<a href="#" class="nav-link p-0 text-white">About</a>
					</li>
				</ul>
			</div>
			<div class="col-4 offset-1 card-header">
				<form>
					<h5 class="text-white">S'inscrire à la newsletter</h5>
					<p class="text-white">Résumé mensuel de ce qui est nouveau et intéressant de notre part.</p>
					<div class="d-flex w-100 gap-2">
						<label for="newsletter1" class="visually-hidden">Email address</label>
						<input id="newsletter1" type="text" class="form-control" placeholder="Email address">
						<button class="btn btn-primary" type="button">Subscribe</button>
					</div>
				</form>
			</div>
		</div>
		<div class="d-flex footer justify-content-between py-4 my-4 border-top card-header rounded">
			<p class="text-white">&copy; 2021 Company, Inc. All rights reserved.</p>
			<ul class="list-unstyled d-flex">
				<li class="ms-3">
					<a class="link-dark" href="#">
						<svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg>
					</a>
				</li>
				<li class="ms-3">
					<a class="link-dark" href="#">
						<svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg>
					</a>
				</li>
				<li class="ms-3">
					<a class="link-dark" href="#">
						<svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg>
					</a>
				</li>
			</ul>
		</div>
	</footer>
</div>

templates/layouts/partials/pagination.html.twig
{#
/**
 * @file
 * Twitter Bootstrap v4 Sliding pagination control implementation.
 *
 * View that can be used with the pagination module
 * from the Twitter Bootstrap CSS Toolkit
 * https://getbootstrap.com/docs/4.5/components/pagination/
 *
 */
#}
{% if pageCount > 1 %}
    <nav>
        {% set classAlign = (align is not defined) ? '' : align=='center' ? ' justify-content-center' : (align=='right' ? ' justify-content-end' : '') %}
        {% set classSize = (size is not defined) ? '' : size=='large' ? ' pagination-lg' : (size=='small' ? ' pagination-sm' : '') %}
        <ul class="pagination{{ classAlign }}{{ classSize }}">

            {% if previous is defined %}
                <li class="page-item">
                    <a class="page-link" rel="prev" href="{{ path(route, query|merge({(pageParameterName): previous})) }}">&laquo;&nbsp;{{ 'label_previous'|trans({}, 'KnpPaginatorBundle') }}</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">&laquo;&nbsp;{{ 'label_previous'|trans({}, 'KnpPaginatorBundle') }}</span>
                </li>
            {% endif %}

            {% if startPage > 1 %}
                <li class="page-item">
                    <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 1})) }}">1</a>
                </li>
                {% if startPage == 3 %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): 2})) }}">2</a>
                    </li>
                {% elseif startPage != 2 %}
                    <li class="page-item disabled">
                        <span class="page-link">&hellip;</span>
                    </li>
                {% endif %}
            {% endif %}

            {% for page in pagesInRange %}
                {% if page != current %}
                    <li class="page-item">
                        <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): page})) }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="page-item active">
                        <span class="page-link">{{ page }}</span>
                    </li>
                {% endif %}

            {% endfor %}

            {% if pageCount > endPage %}
                {% if pageCount > (endPage + 1) %}
                    {% if pageCount > (endPage + 2) %}
                        <li class="page-item disabled">
                            <span class="page-link">&hellip;</span>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): (pageCount - 1)})) }}">{{ pageCount -1 }}</a>
                        </li>
                    {% endif %}
                {% endif %}
                <li class="page-item">
                    <a class="page-link" href="{{ path(route, query|merge({(pageParameterName): pageCount})) }}">{{ pageCount }}</a>
                </li>
            {% endif %}

            {% if next is defined %}
                <li class="page-item">
                    <a class="page-link" rel="next" href="{{ path(route, query|merge({(pageParameterName): next})) }}">{{ 'label_next'|trans({}, 'KnpPaginatorBundle') }}&nbsp;&raquo;</a>
                </li>
            {% else %}
                <li  class="page-item disabled">
                    <span class="page-link">{{ 'label_next'|trans({}, 'KnpPaginatorBundle') }}&nbsp;&raquo;</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}